### ISSUE TITLE
[DESIGN] Searching/found lobby screen

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_myrra#1045]
## 🎨 Design
Ditto.

**Comment by jazimp** [comment]
![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/b6269ca0-c580-47d1-97e9-5b1279a29809)
![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/1dbccf1d-959b-4dec-8055-da19113e6e97)
