### ISSUE TITLE
[FEATURE] Health bar perspective

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_myrra#1048]
## 🚀 Feature
Change the health bar's perspective so that it always faces the camera.

**Comment by martinacantaro** [comment]
We talked about this briefly yesterday, and i would need to clarify if this is a matter of perspective or a matter of rendering. 

To add more detail:
- The health bar is now an object on top of each character's head
- The camera is always focusing on the playing character in each client. Health bar looks stable on the playing character from that fixed perspective, but for enemies moving around on the edges of the screen the health bar distorts as they have different angles relative to the camera.
- We talked about solving this with a rendering camera

What solution does the ticket description request?

**Comment by saugon** [comment]
It could probably be solved in different ways. How would be the approach using a rendering camera? 

I thought it might be resolved by continuously rotating the health bar (everything above the character, in fact) to face the camera. [Here](https://www.youtube.com/watch?v=ViZto58MgjM&ab_channel=xOctoManx) is an example of a possible method to achieve it. Of course we can discuss the best approach.

**Comment by martinacantaro** [comment]
Based on the example you linked, I guess the health bars are only rendered for the client, so that each client sees the health bars at a different angle based on their camera position.
I'm going to go ahead and try out that solution.
