### ISSUE TITLE
[DESIGN] Enhance killfeed design

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_myrra#1051]
Elements that can be used:
- Player names
- Character images

Things not being tracked for the time being:
- Skills 
- Assists

**Comment by jazimp** [comment]
![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/d0e08720-0120-4d9a-9fd2-96273a048b52)

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/1hOcOQfEZAsfDQT1aEj65xP4GHMQVTJyo?usp=drive_link reference + assets

**Comment by jazimp** [comment]
The assets are ready, but the images of each character are missing.
