### ISSUE TITLE
[FEATURE] Main screen background animation

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_myrra#1195]
## 🚀 Feature
Implement a visually appealing animation for the background of the main screen to enhance the overall user experience. The animation should be subtle and complement the theme of the game.

#### Specifications
- The animation should not impact performance significantly.
- Choose a background animation style that aligns with the game's aesthetic.
- Ensure the animation seamlessly loops for a continuous visual effect.
- Test the animation on various devices to ensure responsiveness.

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/1FTIf7EfvHwwSWyvDLeHBAVhN_ju9JPDe?usp=drive_link assets + reference (rocks and thunders)
