### ISSUE TITLE
[FEATURE] Character info improvements

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_myrra#1210]
## 🚀 Feature
1. Update the typology for the arrows to cycle through the characters so they do not look like disabled buttons.
2. Increase the font size of the skill info, maybe 1 or 2 points.
3. Center the screen title.
4. Add a "coming soon" reference to the buttons on the right side (lore, overview and skin) and change them to full opacity.

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/1koTdE5RICL81YsMDn9zVMKpYhl0vC1Ax?usp=drive_link reference + assets

![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/584c4eb8-a761-4afb-9172-a687dd5165a4)
