### ISSUE TITLE
[PAUSED][FEATURE] Loot package

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_myrra#406]
Loot package (LP): is a pickable item that could have different effect when its picked, for example, heal the player or level up a skill.

### Tasks

**Back:**
- Create a LP at X,Y position with a defined effect.
- Apply effect once it's picked.
- Remove LP.

**Front:**
- Listen LP creation message and display it.
- Listen LP deletion and destroy it.

**Comment by martinacantaro** [comment]
Paused. We're tackling this _after_ the First Playable

**Comment by martinacantaro** [comment]
Paused. We're tackling this _after_ the First Playable
