### ISSUE TITLE
[REFACTOR] Switch to URP

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_myrra#449]
Since no render pipeline in set, Unity uses the standard render pipeline (which is the legacy render pipeline).
Let's switch to URP, it should run better on mobile devices and allows us to uses new features.

> Universal Render Pipeline or URP refers to a newer lightweight rendering pipeline designed to run efficiently on all devices, but particularly designed to perform well on mobile and lower tiers of hardware. URP can handle most of what Standard does, but does require some additional conversion of materials in your assets.

**Comment by tvillegas98** [comment]
Addressed in #480
