### ISSUE TITLE
[BUG] Player id not being display after player dies

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_myrra#492]
Tomi: We’re currently displaying the Player id above the character, but if the player dies, in the following rounds the Player id will no longer appear

**Comment by martinacantaro** [comment]
| Character  | Who was Player 1? | Who won? | Name displayed in Round 2? Y/N | 
| ---------- | ------------------- | ---------- | -------------------------------- |
| Muflus | ⭐️ | 🏆 | ✅
| Hack |  |  | ❌

**Comment by martinacantaro** [comment]
| Character  | Who was Player 1? | Who won? | Name displayed in Round 2? Y/N | 
| ---------- | ------------------- | ---------- | -------------------------------- |
| Muflus | ⭐️ |  | ✅
| Hack |  | 🏆 | ✅

**Comment by martinacantaro** [comment]
| Character  | Who was Player 1? | Who won? | Name displayed in Round 2? Y/N | 
| ---------- | ------------------- | ---------- | -------------------------------- |
| Hack | ⭐️ |  | ✅
| Hack |  | 🏆 | ✅
