### ISSUE TITLE
[FEATURE] Add version number to the protocol 

### ISSUE THREAD

**Issue by jrchatruc** [lambdaclass/curse_of_myrra#494]
## 🚀 Feature

The message protocol between client and server should have a version number that is sent when first communicating. If the client and server versions do not match, the connection terminates and a message is shown to the player to update.

The game should also show on the menu both the hash of the server and client code and the latest deployment date

**Comment by AminArria** [comment]
Version checked is unlikely to happen on initial version checks (and termination) is unlikely to be enforced in first iteration of this ticket
