### ISSUE TITLE
[BUG] Cooldowns are not consistent

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_myrra#495]
Cooldowns not always behave like we expect. For example:
- 5s cooldown: sometimes it starts the countdown from 4. 
- 1s cooldown: sometimes the skill is available again almost immediately.

It could be related to the back-front communication. For starters, we can try setting up the cooldown on input setup and handle it from Unity.

**Comment by martinacantaro** [comment]
https://github.com/lambdaclass/curse_of_myrra/pull/438
