### ISSUE TITLE
[FEATURE] When a round ends, wait a few seconds before starting next round

### ISSUE THREAD

**Issue by martinacantaro** [lambdaclass/curse_of_myrra#511]
When someone wins a round, all characters disappear the instant the last punch lands, and if you don't read the message "X wins" it's hard to know if you won or lost. 
Freeze the "game state" for a couple of seconds while the "X wins" message is on screen so it's clear who died and who's alive at the end of the round

**Comment by marco-paulucci** [comment]
Closing as we aren't going to be using rounds.
