### ISSUE TITLE
[BUG] Glitch

### ISSUE THREAD

**Issue by martinacantaro** [lambdaclass/curse_of_myrra#518]
In Android, there are glitches

https://user-images.githubusercontent.com/6120897/252757046-659b2402-a3e3-4229-8260-b39b3190d310.MOV

Possible cause: https://lambdaclass.slack.com/archives/C050K67ME7P/p1689098101818589

**Comment by mztrpln** [comment]
not the best video quality I know, but there are no more glitches in Android 

https://github.com/lambdaclass/curse_of_myrra/assets/17114547/6a16018d-99ed-4788-993d-cd74dd7b92c6

**Comment by mztrpln** [comment]
https://github.com/lambdaclass/curse_of_myrra/assets/17114547/132d996b-4cf1-42a4-84ce-f939cbeef3cb
