### ISSUE TITLE
[FEATURE] Players can choose their name

### ISSUE THREAD

**Issue by AminArria** [lambdaclass/curse_of_myrra#527]
## 🚀 Feature

A player should be able to choose a name for themselves (maybe in main lobbies screen?) and then we will propagate that to the games so they show up instead of the player IDs (not replace, just for UI stuff, internally should be IDs)

**Comment by jazimp** [comment]
![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/6fb856fc-d174-4a8d-9026-cdfafd6eca6e)
