### ISSUE TITLE
[REFACTOR] Settings Panel

### ISSUE THREAD

**Issue by marco-paulucci** [lambdaclass/curse_of_myrra#530]
## 🚧 Refactor

- [x] Implement a ⚙️ button at the top right of the screen, which opens a togglable right-panel
- [x] Include all buttons that are currently in the main canvas (interpolation, sound, ghost, prediction, bots)
- [x] Include all buttons from the left "pause" panel: back to lobbies & music slider
- [x] Remove the left "pause" panel

**Comment by BertovDev** [comment]
Also this is necessary because now the kill feed overlaps the pause button
