### ISSUE TITLE
[BUG] Multiple click events received when clicking a button.

### ISSUE THREAD

**Issue by ncontinanza** [lambdaclass/curse_of_myrra#536]
## 🐛 Bug Report

This bug only happens when playing the game in the Unity editor.
When using a mouse to click on a back button, a second click will be received if in the next scene there is another button under the mouse pointer. This behaviour can be easily verified if, after clicking a button, the pointer is quickly moved to a side of the screen or somewhere else where there won't be a button in the next scene. On the contrary, if the button is clicked in a spot where there is a button in the next scene, this effect will be observed. 

### Steps to Reproduce

1. Start the game in the Unity editor. 
2. In the lobbies scene, click "New Lobby".
3. Click on the rightmost region of the "Back" button (so that when the scene changes the pointer is over the "New Lobby" button), and keep the pointer still after clicking.

https://github.com/lambdaclass/curse_of_myrra/assets/17294394/b21b1114-9071-4c8d-bfd4-49f7bb225e92

**Comment by BertovDev** [comment]
I think this is happening because the UI is set as Mobile so a mouse hover will be detected as a click, but it is true that in mobile you can spam the buttons and create unlimited lobbies.
