### ISSUE TITLE
[FEATURE] Add music to Lobby phase

### ISSUE THREAD

**Issue by martinacantaro** [lambdaclass/curse_of_myrra#540]
We could use this song:
https://drive.google.com/file/d/18Ii8k_758oXd-TvpWkUoMQmYXisyAEyj/view?usp=drive_link

Or this one, but only if we use a different one for the Otobi Arena: https://drive.google.com/file/d/1yjl2Q1xec92yOscwgfWMniPLmxeJehYS/view?usp=drive_link

**Comment by ncontinanza** [comment]
We decided to go with the second one, at least temporarily.
