### ISSUE TITLE
[BUG] Rage + Leap = Broken movement 

### ISSUE THREAD

**Issue by BertovDev** [lambdaclass/curse_of_myrra#592]
## 🐛 Bug Report

With muflus if you perform a Leap while you are in Rage mode. Ability movement is broken

https://github.com/lambdaclass/curse_of_myrra/assets/62818001/4a38f37c-41ff-4898-9a6b-59dd7021c289

**Comment by mztrpln** [comment]
@BertovDev looks like it's been solved 
https://github.com/lambdaclass/curse_of_myrra/assets/17114547/ab63864b-df66-4e0a-936f-7da62c374ddb

**Comment by mztrpln** [comment]
@BertovDev looks like it's been solved 

https://github.com/lambdaclass/curse_of_myrra/assets/17114547/2d447bc4-e987-49f3-b39d-376944abca50

**Comment by mztrpln** [comment]
@BertovDev looks like it's been solved

**Comment by marco-paulucci** [comment]
You're right, I just tested it as well. Thanks!
