### ISSUE TITLE
[BUG] When a player dies, its state is incorrect.

### ISSUE THREAD

**Issue by ncontinanza** [lambdaclass/curse_of_myrra#593]
## 🐛 Bug Report

When playing an 1v1 match, when a player playing with H4ck kills the other player (whether it's H4ck or Muflus), the losing player's state is incorrect. Its health does not drop to zero, and its status is not changed to Dead.

### Steps to Reproduce
1. At the end of the Update() method of CustomLevelManager.cs, paste the following piece of code:
```
var gamePlayer = SocketConnectionManager.Instance.gamePlayers.Find(gp => gp.Id == gamePlayerId);
if (gamePlayer != null) 
{
   print(gamePlayer.Status);
   print(gamePlayer.Health);
}
```
2. Start a new game and make sure that the editor or mobile build running the code above is the one that dies in the match. 
3. Use H4ck to kill your opponent. 
4. Notice how your opponent's life is not equal to 0, and its status is not Dead.

**Comment by BertovDev** [comment]
I believe we can fix this with a little hack :
`gamePlayers.Find(el => el.Id != winnerPlayer.Item1.Id).Health = 0;`
inside the case `GameEventType.GameFinished` of the `SocketConnectionManager`
