### ISSUE TITLE
Feedback Thread

### ISSUE THREAD

**Issue by marco-paulucci** [lambdaclass/curse_of_myrra#608]
This living issue is to allow developers to make suggestions to make the game more balanced and fun. 
We might move this to a different place eventually. 

**Dos:**
- Report imbalanced characters or skills (too strong or weak)
- Report gameplay mechanics which you don't consider fun
- Report mechanics or skills you did really like (this helps move the design in that direction)

**Don'ts:**
- Report bugs (create an issue instead)

**Comment by phklive** [comment]
Test comment
