### ISSUE TITLE
[BUG] Animation restart when moving diagonally

### ISSUE THREAD

**Issue by marco-paulucci** [lambdaclass/curse_of_myrra#609]
## 🐛 Bug Report

The walking animation interrupts itself and resets when walking perfectly diagonally.

How to reproduce:
- walk diagonally in a perfect 45/135/225/315 degree angle
- easier to reproduce in PC where pressing two keys will give you perfect angle (i.e. right and up for 45deg)

Tested in
- PC
- iOS

**Comment by tvillegas98** [comment]
Fixed in #515
