### ISSUE TITLE
[BUG] Muflus can't attack bot

### ISSUE THREAD

**Issue by mgrunwaldt** [lambdaclass/curse_of_myrra#654]
## 🐛 Bug Report

Muflus attacks bots but doesn't hurt them. Might be related to https://github.com/lambdaclass/curse_of_myrra/issues/653 

https://github.com/lambdaclass/curse_of_myrra/assets/22064054/3a8faa7b-d745-47d8-8672-8195e414f1b0

Tested in Unitiy iOS Simulator, iPhone 12

**Comment by manucamejo** [comment]
Fixed!
