### ISSUE TITLE
[BUG] Muflus locked after using Leap

### ISSUE THREAD

**Issue by marco-paulucci** [lambdaclass/curse_of_myrra#659]
## 🐛 Bug Report

Muflus locks himself sometimes after using Leap. Initially we thought this was a disconnection but the player is still connected.

https://github.com/lambdaclass/curse_of_myrra/assets/20408709/b5246ffb-3188-46fd-ac83-5a1b5452f861

**Comment by mztrpln** [comment]
Refer to issue #526 and #592. It appears to've been solved.
