### ISSUE TITLE
[BUG] - Set Muflus skills according to what the Notion says

### ISSUE THREAD

**Issue by tvillegas98** [lambdaclass/curse_of_myrra#662]
## 🐛 Bug Report
There was an issue saying that we should change Muflus skills location in the UI (this one #621), and we did change it in #611. Now we should restore it and fix it according to what the Notion says now.

**Comment by marco-paulucci** [comment]
Hi!

It's also proper in the Characters.json: 
https://github.com/lambdaclass/curse_of_myrra/blob/main/client/Assets/StreamingAssets/Characters.json
