### ISSUE TITLE
[FEATURE] Uma - Xanda's Mark

### ISSUE THREAD

**Issue by marco-paulucci** [lambdaclass/curse_of_myrra#804]
## 🚀 Feature

Active Skill2 

- [x] Targets an area (like Leap) 
- [x] Search SkillRange distance of the targeted point for a single target. Selects the closest one to targetpoint.
- [ ] If there is no target found the skill cancels (no cooldown)
- [x] Target is inflicted with Mark3, it causes damage received to D'agna to be 50% shared with marked target
- [ ] This effect cannot kill enemies! at most reduce their HP to 1.
- [x] Mark lasts for (Duration=8000ms)
- [x] Mark3 client feedback
- [x] 9000ms cd

⚠️ Marks Info
- Applying the mark on a target which already has that mark resets the duration, rather than stack
- Only Uma and targets affected by Marks should see their feedback.
- Uma should not see nor interact with Marks from other Umas in any way

**Comment by martinacantaro** [comment]
- [ ] Make sure Xanda's Mark is consistently named "skill 2" accross UI, C# scripts and backend
- [ ] Use the "lamp" button for this skill in the UI

**Comment by martinacantaro** [comment]
It would be cool to have a visual feedback when Uma is hurt that indicates that her damage was shared with her mark

**Comment by martinacantaro** [comment]
> It would be cool to have a visual feedback when Uma is hurt that indicates that her damage was shared with her mark

Or maybe a "shield-like" effect on Uma
