### ISSUE TITLE
[REFACTOR] New Muflus model and animations

### ISSUE THREAD

**Issue by BertovDev** [lambdaclass/curse_of_myrra#842]
## 🚧 Refactor

Implement new Muflus model and map each animation.
Files: https://drive.google.com/drive/u/0/folders/1AebR5Y8HU-RxePVr0VhVoBdrowqv-NHr

#### Ready to map
- [x] Idle
- [x] Walking
#### Pending
- Crush (basic)
- Leap (special)
- Winner
- Defeated

**Comment by mgrunwaldt** [comment]
blocker: depends on contractor

**Comment by BertovDev** [comment]
<img width="614" alt="Captura de pantalla 2023-11-07 a la(s) 11 45 50" src="https://github.com/lambdaclass/curse_of_myrra/assets/62818001/19cc705f-68d6-4573-8e04-38f53d7dcc2c">

- The 10 Muflus were tested with 9 models and 1 real player.

Conclusion:
Almost same Performance but so much more quality in the Model. Also New Muflus have 2 skinnedMesh because it includes the weapon.
