### ISSUE TITLE
[FEATURE] Make H4CK's Basic Multishot + aim

### ISSUE THREAD

**Issue by mgrunwaldt** [lambdaclass/curse_of_myrra#843]
## 🚀 Feature

- [ ] replace slingshot's mechanics with multishots, only 3 missiles instead of 5 (no auto-aim)
- [ ] reduce the damage by 30% 
- [ ] with the button free'd by multishot removal, add the ultimate again (make sure it's ordered properly at the top)

**Comment by marco-paulucci** [comment]
Hack's basic is meant to be like multishot though? 🤔
