### ISSUE TITLE
[DESIGN] Item 3d Model

### ISSUE THREAD

**Issue by mgrunwaldt** [lambdaclass/curse_of_myrra#853]
## 🎨 Design

1. Look in Unity Asset Store if there's any 3d crate that has the style of what we're looking for. 
2. If not, define concept art for item crates
3. Then create 3d models and add them to game

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/1lx6rUiLWe9kkaKU_93KaiguaYHG4BZQf?usp=drive_link fbx with texture

**Comment by jazimp** [comment]
![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/a83c1e16-126c-4e0c-a4a2-ec4014c18470)
![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/908cba4a-1ffa-4b91-a82a-4aafd60fa54d)
![Image](https://github.com/lambdaclass/curse_of_myrra/assets/134973476/e72eb11a-9f8c-448a-b285-69994f27bfca)
