### ISSUE TITLE
[DESIGN] Different HP Bar colors (instead of circles at the feet)

### ISSUE THREAD

**Issue by marco-paulucci** [lambdaclass/curse_of_myrra#887]
## 🎨 Design

We could use different health bar colors for opponents/player to make it easier to tell them apart.

- [x] remove the circle at the feet of characters
- [ ] change the color of our own health bar (could be green or blue and see which looks best)

**Comment by marco-paulucci** [comment]
related #888

**Comment by mgrunwaldt** [comment]
<img width="280" alt="image" src="https://github.com/lambdaclass/curse_of_myrra/assets/22064054/578b0992-8d66-4534-afee-b3cf636b8963">
one color for self and one for all others
