### ISSUE TITLE
[FEATURE] Map sounds with skills

### ISSUE THREAD

**Issue by BertovDev** [lambdaclass/curse_of_myrra#895]
## 🚀 Feature

 Map sounds with each skill.

**Comment by martinacantaro** [comment]
Leaving this here for reference: my doc with reviews on the previous sounds https://www.notion.so/lambdaclass/Music-feedback-17fb02c093d040bdbe9a5878e02d7a31

**Comment by martinacantaro** [comment]
If we have time: Add UI Click sounds? https://assetstore.unity.com/packages/audio/sound-fx/free-ui-click-sound-pack-244644
