### ISSUE TITLE
[FEATURE] Centralize strings

### ISSUE THREAD

**Issue by marco-paulucci** [lambdaclass/curse_of_myrra#915]
## 🚀 Feature

Strings should be centralized in a location, rather than scattered across various prefabs and objects. This will make it much better to iterate on skill descriptions, fix typos, and in the future, localization features.

**Comment by ncontinanza** [comment]
Useful resources:

- https://docs.unity3d.com/Packages/com.unity.localization@1.4/manual/QuickStartGuideWithVariants.html
- https://docs.unity3d.com/Packages/com.unity.localization@1.4/manual/StringTables.html
- https://www.youtube.com/watch?v=NFn74l2WA_8

**Comment by marco-paulucci** [comment]
adding to backlog
