### ISSUE TITLE
[BUG] The deathcam is not spectating the right player

### ISSUE THREAD

**Issue by saugon** [lambdaclass/curse_of_myrra#980]
## 🐛 Bug Report
Once a player gets killed, the camera should start following the player who did it, but sometimes it starts following someone else.

### How the logic should be:
- When player A is killed by player B, they should see the death splash and spectate player B.
- If player B is killed by player C, A should spectate player C.
- If player B (or C, or whomever A is spectating) is killed by the death zone, they should spectate another player who is alive (the first one who is alive in the list of players)
- When the match ends and someone finally wins, player A should see the death splash (player A's character, A's amount of kills, etc) and a message that says who won the match.

Reference: https://github.com/lambdaclass/curse_of_myrra/issues/857

**Comment by tkz00** [comment]
We tried to replicate the error in the main branch multiple times but we weren't able to, since the bug first appeared in a branch with multiple tickets to test we think it might've been related to that.
